'use client';
import { useMemo, useState } from 'react';
type Movement = { id:string; movement_type:string; movement_date:string; quantity:number; notes:string|null };
const labels: Record<string,string> = { purchase:'Compra', sale:'Venta', birth:'Nacimiento', death:'Baja', transfer_in:'Transferencia entrada', transfer_out:'Transferencia salida', adjustment:'Ajuste' };
export default function MovementsTable({ movements }: { movements: Movement[] }) {
 const [type,setType]=useState('all'); const [query,setQuery]=useState(''); const filtered=useMemo(()=>movements.filter(m=>(type==='all'||m.movement_type===type)&&(!query||(m.notes||'').toLowerCase().includes(query.toLowerCase()))),[movements,type,query]);
 function exportCsv(){const rows=[['Fecha','Tipo','Cantidad','Notas'],...filtered.map(m=>[m.movement_date,labels[m.movement_type]||m.movement_type,String(m.quantity),m.notes||''])];const csv=rows.map(r=>r.map(v=>`"${v.replaceAll('"','""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='movimientos.csv';a.click();URL.revokeObjectURL(url)}
 return <><div className="table-toolbar"><input placeholder="Buscar en notas…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={type} onChange={e=>setType(e.target.value)}><option value="all">Todos los tipos</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button className="button secondary" onClick={exportCsv}>Exportar CSV</button></div>{filtered.length?<><p className="table-result">Mostrando {filtered.length} de {movements.length} movimientos</p><table><thead><tr><th>Fecha</th><th>Tipo</th><th>Cantidad</th><th>Notas</th></tr></thead><tbody>{filtered.map(m=><tr key={m.id}><td>{m.movement_date}</td><td>{labels[m.movement_type]||m.movement_type}</td><td>{m.quantity}</td><td>{m.notes||'—'}</td></tr>)}</tbody></table></>:<div className="empty"><h3>{movements.length?'No hay coincidencias':'Todavía no hay movimientos'}</h3><p>Los movimientos registrados aparecerán aquí.</p></div>}</>;
}
